server:
  port: 8080
logging:
  level:
    com.ogutcenali: WARN
  file:
    name: project.log
  logback:
    rollingpolicy:
      max-file-size: 20MB
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/challange
    username: postgres
    password: Telefon310
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mail:
    username: ${mailusername}
    password: ${mailpassword}
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
jwt:
  secretKey: ${PASSWORD}

redis:
  host: "localhost"
  port: 6379